#!/usr/bin/env node
// Criteria matrix: for every one of the policy-breakdown parameters, which deterministic consumer checks it.
//
//   node scripts/criteria-matrix.mjs            # writes docs/policy-criteria-matrix.md
//
// tests/policy-breakdown-criteria.test.mjs imports criteriaMatrix() and fails when any parameter is extracted
// but never checked anywhere.

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { SECTIONS } from '../src/modules/policy-breakdown/sections/index.js';
import { CARD_FIELDS } from '../src/modules/policy-breakdown/consumers/emergency-card.js';
import { POLICY_STATUS_GROUPS } from '../src/modules/policy-breakdown/consumers/policy-status.js';

const moduleRoot = new URL('../src/modules/policy-breakdown/', import.meta.url);
const source = path => readFileSync(new URL(path, moduleRoot), 'utf8');

export const CONSUMERS = Object.freeze({
  estimate: 'Planned-procedure cost range (POST /estimates)',
  procedure_check: 'Planned-procedure eligibility checklist and steps (POST /procedure-checks, also inside /estimates)',
  emergency_card: 'Emergency card for the human operator (GET /emergency-card)',
  policy_overview: 'Policy overview: documents, servicing, membership, benefits, insurer, household, regulation, renewal (GET /policy-status)',
  analysis: 'Input to the deterministic sections 10–12',
  cross_check: 'Consistency rule between parameters (blocks readiness when critical)',
  readiness: 'Critical: a person must confirm it before the record is ready',
});

export function criteriaMatrix() {
  const estimate = source('consumers/estimate.js');
  const check = source('consumers/procedure-check.js');
  const crossChecks = source('assembly/cross-checks.js');
  const analysis = ['sections/s10-insurer-quality.js', 'sections/s11-household.js', 'sections/s12-regulatory.js'].map(source).join('\n');
  const card = new Set(Object.values(CARD_FIELDS).flat());
  const overview = new Set(Object.values(POLICY_STATUS_GROUPS).flat());
  return SECTIONS.flatMap(section => section.parameters.map(parameter => {
    const literal = `'${parameter.key}'`;
    const consumers = [];
    if (estimate.includes(literal)) consumers.push('estimate');
    if (check.includes(literal)) consumers.push('procedure_check');
    if (card.has(parameter.key)) consumers.push('emergency_card');
    if (overview.has(parameter.key)) consumers.push('policy_overview');
    if (section.kind === 'extraction' && analysis.includes(literal)) consumers.push('analysis');
    if (crossChecks.includes(literal)) consumers.push('cross_check');
    if (parameter.critical) consumers.push('readiness');
    return { section: section.number, sectionTitle: section.title, key: parameter.key, label: parameter.label, critical: parameter.critical, visibility: parameter.visibility, consumers };
  }));
}

function markdown(rows) {
  const lines = [
    '# Policy criteria matrix',
    '',
    'Generated by `node scripts/criteria-matrix.mjs`. Every parameter is shown in the record view (`GET /sections`);',
    'this table lists where each one is also checked. `tests/policy-breakdown-criteria.test.mjs` fails when a',
    'parameter has no checking consumer.',
    '',
    ...Object.entries(CONSUMERS).map(([id, text]) => `- **${id}** — ${text}`),
    '',
  ];
  for (const section of SECTIONS) {
    const sectionRows = rows.filter(row => row.section === section.number);
    lines.push(`## ${section.number}. ${section.title}`, '', '| Parameter | Key | Critical | Checked by |', '|---|---|---|---|');
    for (const row of sectionRows) lines.push(`| ${row.label} | \`${row.key}\` | ${row.critical ? 'yes' : ''} | ${row.consumers.join(', ')} |`);
    lines.push('');
  }
  const total = rows.length;
  const checked = rows.filter(row => row.consumers.length).length;
  lines.push(`**${checked} of ${total} parameters are checked by at least one consumer.**`, '');
  return lines.join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const rows = criteriaMatrix();
  writeFileSync(new URL('../docs/policy-criteria-matrix.md', import.meta.url), markdown(rows));
  const unchecked = rows.filter(row => !row.consumers.length);
  console.log(`${rows.length - unchecked.length}/${rows.length} parameters checked${unchecked.length ? `; unchecked: ${unchecked.map(row => row.key).join(', ')}` : ''}. Wrote docs/policy-criteria-matrix.md`);
  process.exitCode = unchecked.length ? 1 : 0;
}
